'use strict'

// This generates the scramble lookup table, used to scramble the data
// payload of a sector. The scrambling is done by XORing the data with a
// pseudo-random sequence, generated by a 15 bits linear feedback shift
// register. When processing data sectors, the 2340 bytes of payload
// are scrambled using this algorithm according to the spec.
const scrambleLUT = []
let shift = 1
for (let n = 0; n < 2340; n++) {
  scrambleLUT[n] = shift & 0xff
  for (let b = 0; b < 8; b++) {
    shift = (((shift << 14) ^ (shift << 13)) & 0x4000) | (shift >> 1)
  }
}

exports.scrambleLUT = scrambleLUT
